language: python

cache:
  - pip

python:
  - "2.7"
  - "3.6"

before_install:
  - sudo apt-get install libicu-dev -y

install:
  - pip install --upgrade -q PyICU cchardet six twine nose coveralls
  - pip install -e .

script:
  - nosetests --with-coverage --cover-package=normality

after_success:
  - coveralls
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
    fi
