language: python

cache:
  - pip

python:
  - "3.7"

before_install:
  - sudo apt-get install libicu-dev -y

install:
  - pip install --upgrade -q PyICU cchardet coveralls
  - pip install -e '.[dev]'

script:
  - mypy normality
  - nosetests --with-coverage --cover-package=normality

after_success:
  - coveralls
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
    fi
